package dev.rajeev.shortener.repository;

import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Versioned, idempotent, in-code schema migration. Small enough at v1 to keep explicit; a Flyway
 * migration set is the drop-in replacement once the schema grows (documented in the limitations).
 * SQL is kept to the H2/PostgreSQL common subset.
 */
public class SchemaMigrator {

    private static final Logger log = LoggerFactory.getLogger(SchemaMigrator.class);
    public static final int CURRENT_VERSION = 1;

    private final JdbcTemplate jdbc;

    public SchemaMigrator(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    public int migrate() {
        jdbc.execute("CREATE TABLE IF NOT EXISTS schema_version (version INTEGER NOT NULL)");
        Integer version = jdbc.query("SELECT version FROM schema_version", rs -> rs.next() ? rs.getInt(1) : null);
        if (version == null) {
            createV1();
            jdbc.update("INSERT INTO schema_version(version) VALUES (1)");
            version = 1;
        }
        log.info("schema version {}", version);
        return version;
    }

    private void createV1() {
        for (String ddl : List.of(
                """
                CREATE TABLE IF NOT EXISTS links (
                  code        VARCHAR(32)   PRIMARY KEY,
                  target_url  VARCHAR(8192) NOT NULL,
                  created_at  TIMESTAMP     NOT NULL,
                  deleted_at  TIMESTAMP,
                  custom      BOOLEAN       NOT NULL DEFAULT FALSE,
                  owner_id    VARCHAR(128)
                )""",
                """
                CREATE TABLE IF NOT EXISTS idempotency_keys (
                  idem_key    VARCHAR(128) PRIMARY KEY,
                  code        VARCHAR(32)  NOT NULL,
                  created_at  TIMESTAMP    NOT NULL
                )""",
                """
                CREATE TABLE IF NOT EXISTS clicks (
                  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  code        VARCHAR(32)  NOT NULL,
                  occurred_at TIMESTAMP    NOT NULL,
                  referrer    VARCHAR(255) NOT NULL,
                  user_agent  VARCHAR(64)  NOT NULL
                )""",
                "CREATE INDEX IF NOT EXISTS idx_clicks_code_time ON clicks(code, occurred_at)")) {
            jdbc.execute(ddl);
        }
    }
}
