package dev.rajeev.shortener.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import dev.rajeev.shortener.domain.Link;
import java.time.Clock;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/**
 * Upgrade path: a database created by schema v1 (no expires_at column) must be migrated in place,
 * keep its rows, read them back with expiresAt = null, and survive being opened twice.
 */
class SchemaUpgradeTest {

    private static org.h2.jdbcx.JdbcDataSource v1Database() {
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        JdbcTemplate jdbc = new JdbcTemplate(ds);
        jdbc.execute("CREATE TABLE schema_version (version INTEGER NOT NULL)");
        jdbc.update("INSERT INTO schema_version(version) VALUES (1)");
        jdbc.execute("CREATE TABLE links (code VARCHAR(32) PRIMARY KEY, target_url VARCHAR(8192) NOT NULL, created_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, custom BOOLEAN NOT NULL DEFAULT FALSE, owner_id VARCHAR(128))");
        jdbc.execute("CREATE TABLE idempotency_keys (idem_key VARCHAR(128) PRIMARY KEY, code VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL)");
        jdbc.execute("CREATE TABLE clicks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(32) NOT NULL, occurred_at TIMESTAMP NOT NULL, referrer VARCHAR(255) NOT NULL, user_agent VARCHAR(64) NOT NULL)");
        jdbc.update("INSERT INTO links(code, target_url, created_at) VALUES ('legacy1', 'https://example.com/', TIMESTAMP '2026-01-01 00:00:00')");
        return ds;
    }

    private static JdbcLinkRepository open(org.h2.jdbcx.JdbcDataSource ds) {
        return new JdbcLinkRepository(new JdbcTemplate(ds), new TransactionTemplate(new DataSourceTransactionManager(ds)), Clock.systemUTC());
    }

    @Test
    void addsExpiresAtBumpsTheVersionAndPreservesLegacyRows() {
        org.h2.jdbcx.JdbcDataSource ds = v1Database();
        JdbcLinkRepository repo = open(ds);
        assertEquals(2, new JdbcTemplate(ds).queryForObject("SELECT version FROM schema_version", Integer.class));
        Link legacy = repo.findByCode("legacy1").orElseThrow();
        assertEquals("https://example.com/", legacy.targetUrl());
        assertNull(legacy.expiresAt());
        Instant expires = Instant.parse("2030-01-01T00:00:00Z");
        repo.insert(new Link("new0001", "https://example.com/n", Instant.parse("2026-02-01T00:00:00Z"), null, expires, false, null));
        assertEquals(expires, repo.findByCode("new0001").orElseThrow().expiresAt());
    }

    @Test
    void isIdempotentWhenReopened() {
        org.h2.jdbcx.JdbcDataSource ds = v1Database();
        open(ds);
        open(ds);
        assertEquals(2, new JdbcTemplate(ds).queryForObject("SELECT version FROM schema_version", Integer.class));
        assertEquals(1, new JdbcTemplate(ds).queryForObject("SELECT COUNT(*) FROM schema_version", Integer.class));
    }
}
